/* Generated By:JJTree: Do not edit this line. G:/eclipse/jep/src/org/nfunk/jep\ParserTreeConstants.java */

package org.nfunk.jep;

/**
 * 
 * @author matog
 * $Id: ParserTreeConstants.java,v 1.2 2012/01/17 12:06:35 matog Exp $
 */
public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTFUNNODE = 2;
  public int JJTVARNODE = 3;
  public int JJTCONSTANT = 4;


  public String[] jjtNodeName = {	// NOSONAR Malicious code vulnerability - Field should be moved out of an interface and made package protected  neriesime
    "Start",
    "void",
    "FunNode",
    "VarNode",
    "Constant",
  };
}
