/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_study_HelloJNI */

#ifndef _Included_java_study_HelloJNI
#define _Included_java_study_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_study_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_1study_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
