/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_study_HelloJNICpp */

#ifndef _Included_java_study_HelloJNICpp
#define _Included_java_study_HelloJNICpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_study_HelloJNICpp
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_1study_HelloJNICpp_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
