/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_study_TestJNIPrimitive */

#ifndef _Included_java_study_TestJNIPrimitive
#define _Included_java_study_TestJNIPrimitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_study_TestJNIPrimitive
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_java_1study_TestJNIPrimitive_average
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     java_study_TestJNIPrimitive
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_1study_TestJNIPrimitive_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
